#ifndef WIDGETS_HPP
#define WIDGETS_HPP

#include "flux_action.hpp"
#include "flux_collection.hpp"
#include "flux_conditional.hpp"
#include "flux_display.hpp"
#include "flux_image.hpp"
#include "flux_input.hpp"
#include "flux_keyboard.hpp"
#include "flux_layout.hpp"
#include "flux_structure.hpp"
#include "flux_icons.hpp"
#include "flux_colorpicker.hpp"
#include "flux_overlays.hpp"
#include "flux_histogram.hpp"
#include "flux_hsl_panel.hpp"
#include "flux_tonecurve.hpp"
#include "flux_splitview.hpp"
#include "flux_menubar.hpp"
#include "flux_datepicker.hpp"
#include "flux_tabview.hpp"
#include "flux_treeview.hpp"

#include "flux_toast.hpp"
#include "flux_input_extended.hpp"
#include "flux_accordion.hpp"
#include "flux_audioplayer.hpp"
#include "flux_videoplayer.hpp"
#include "mic.hpp"
// #include "camera_widget.hpp"
#include "flux_future_builder.hpp"
#include "flux_file_picker.hpp"
#include "flux_graph.hpp"
#include "flux_padding.hpp"
// #include "flux_stream_builder.hpp"
#include "flux_circular_progress.hpp"
#endif // WIDGETS_HPP