# config/AppConfig.cmake
file(READ "${CMAKE_CURRENT_LIST_DIR}/AppConfig.json" FLUX_CONFIG_JSON)

string(JSON FLUX_APP_NAME      GET ${FLUX_CONFIG_JSON} name)
string(JSON FLUX_APP_BUNDLE_ID GET ${FLUX_CONFIG_JSON} bundleId)
string(JSON FLUX_APP_VERSION   GET ${FLUX_CONFIG_JSON} version)
string(JSON FLUX_APP_BUILD     GET ${FLUX_CONFIG_JSON} build)