name: Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        abi:
          - arm64-v8a
          - x86_64

    name: Android ${{ matrix.abi }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Configure
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK" >> $GITHUB_ENV

          cmake -S . -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-28 \
            -DFLUX_BUILD_EXAMPLES=OFF

      - name: Build
        run: cmake --build build --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flux-android-${{ matrix.abi }}-release
          path: |
            build/**/*.a
            build/**/*.so
            include/