name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    name: macOS ${{ matrix.config }} (AppleClang)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure
        run: |
          cmake -S . -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DFLUX_BUILD_EXAMPLES=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Upload artifacts
        if: matrix.config == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: flux-macos-arm64-release
          path: |
            build/**/*.a
            include/